services:
  postgres:
    container_name: postgres
    image: postgis/postgis:16-3.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../../../settings/.database.env
    ports:
      - "${POSTGRES_PORT}:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ../../../settings/.database.env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

networks:
  postgres_network:
    driver: bridge
volumes:
  postgres_data:
  pgadmin_data: