services:
  postgres:
    container_name: postgres
    image: postgis/postgis:16-3.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../../../settings/.database.env
    ports:
      - "${POSTGRES_PORT}:5432"
volumes:
  postgres_data: