services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: