services:
  postgres:
    container_name: postgres
    image: postgis/postgis:16-3.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./settings/initdb:/docker-entrypoint-initdb.d/
    env_file:
      - ./settings/.env
    expose:
      - "5432"
    networks:
      - matcha-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./settings/.env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./settings/servers.json:/pgadmin4/servers.json
    networks:
      - matcha-network
  flask-backend:
    container_name: flask-backend
    build:
      context: ./backend_rewrite
      dockerfile: Dockerfile
    env_file:
      - ./settings/.env
    ports:
      - "${FLASK_PORT}:5000"
    depends_on:
      - postgres
    volumes:
      - flask-backend_data:/app
    networks:
      - matcha-network
  angular-frontend:
    container_name: angular-frontend
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - flask-backend
    networks:
      - matcha-network

networks:
  matcha-network:
    driver: bridge
volumes:
  postgres_data:
  pgadmin_data:
  flask-backend_data: